# Generated by Django 6.1 on 2026-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterysubmission',
            name='city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('ekb', 'Екатеринбург'), ('nnovgorod', 'Нижний Новгород'), ('samara', 'Самара'), ('omsk', 'Омск'), ('chelyabinsk', 'Челябинск'), ('rostov', 'Ростов-на-Дону'), ('ufa', 'Уфа'), ('krasnoyarsk', 'Красноярск'), ('voronezh', 'Воронеж'), ('perm', 'Пермь'), ('volgograd', 'Волгоград'), ('other', 'Другой')], default='moscow', max_length=50, verbose_name='Город'),
        ),
    ]
