# Generated by Django 6.1 on 2026-01-28 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_batterysubmission_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('icon', models.CharField(blank=True, default='♻️', max_length=10, verbose_name='Иконка (emoji)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Тип материала',
                'verbose_name_plural': 'Типы материалов',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='batterysubmission',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Сдача вторсырья', 'verbose_name_plural': 'Сдачи вторсырья'},
        ),
        migrations.AlterField(
            model_name='batterysubmission',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='batterysubmission',
            name='recyclable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batteries.recyclabletype', verbose_name='Тип материала'),
        ),
    ]
