# Generated by Django 6.1 on 2026-01-28 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_recyclabletype_alter_batterysubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterysubmission',
            name='recyclable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batteries.recyclabletype', verbose_name='Тип материала'),
        ),
    ]
